import type { BrokerItem } from "@/app/components/module/picks/BrokerSelectSheet";

/**
 * BO `apps/admin/app/routers/broker.py` 의 BROKERS 와 동일하게 유지.
 * `/api/brokers` 실패·빈 응답 시 앱에서 증권사 선택 시트가 비지 않도록 폴백.
 */
export const DEFAULT_BROKERS: BrokerItem[] = [
  {
    id: "samsung",
    name: "삼성증권",
    short: "삼성",
    logo_color: "#1428A0",
    mobile_web: "https://m.samsungpop.com",
    deep_link: "samsungpop://",
    android_store: "https://play.google.com/store/apps/details?id=com.samsungpop.mfacesandroid",
  },
  {
    id: "mirae",
    name: "미래에셋증권",
    short: "미래에셋",
    logo_color: "#E8001F",
    mobile_web: "https://securities.miraeasset.com/hkd/hkd8000/h/hkd8000h.do",
    deep_link: "miraeasset://",
    android_store: "https://play.google.com/store/apps/details?id=com.miraeasset.brokerage",
  },
  {
    id: "korea_invest",
    name: "한국투자증권",
    short: "한국투자",
    logo_color: "#FF6600",
    mobile_web: "https://m.truefriend.com",
    deep_link: "truefriend://",
    android_store: "https://play.google.com/store/apps/details?id=com.truefriend.mobiletradingpad",
  },
  {
    id: "nh",
    name: "NH투자증권",
    short: "NH투자",
    logo_color: "#009B3A",
    mobile_web: "https://m.nhqv.com",
    deep_link: "nhqv://",
    android_store: "https://play.google.com/store/apps/details?id=com.nhqv.SmartmAllApp",
  },
  {
    id: "kb",
    name: "KB증권",
    short: "KB",
    logo_color: "#FFB800",
    mobile_web: "https://m.kbsec.com",
    deep_link: "kbsmart://",
    android_store: "https://play.google.com/store/apps/details?id=com.kbfg.kbsmart",
  },
  {
    id: "shinhan",
    name: "신한투자증권",
    short: "신한",
    logo_color: "#0046FF",
    mobile_web: "https://m.shinhaninvest.com",
    deep_link: "shinhaninvest://",
    android_store: "https://play.google.com/store/apps/details?id=com.shinhaninvest.android8",
  },
  {
    id: "kiwoom",
    name: "키움증권",
    short: "키움",
    logo_color: "#FF0000",
    mobile_web: "https://m.kiwoom.com",
    deep_link: "kiwoom://",
    android_store: "https://play.google.com/store/apps/details?id=com.kiwoom.hero",
  },
  {
    id: "daishin",
    name: "대신증권",
    short: "대신",
    logo_color: "#004098",
    mobile_web: "https://m.daishin.com",
    deep_link: "daishin://",
    android_store: "https://play.google.com/store/apps/details?id=com.daishin.cybosplus.lite",
  },
  {
    id: "meritz",
    name: "메리츠증권",
    short: "메리츠",
    logo_color: "#E8001F",
    mobile_web: "https://m.meritz.co.kr",
    deep_link: "meritz://",
    android_store: "https://play.google.com/store/apps/details?id=com.meritz.mstock",
  },
  {
    id: "hana",
    name: "하나증권",
    short: "하나",
    logo_color: "#009999",
    mobile_web: "https://m.hanasec.co.kr",
    deep_link: "hanas://",
    android_store: "https://play.google.com/store/apps/details?id=com.hanabank.hanas",
  },
  {
    id: "ebest",
    name: "이베스트투자증권",
    short: "이베스트",
    logo_color: "#0066CC",
    mobile_web: "https://m.ebest.co.kr",
    deep_link: "efriend://",
    android_store: "https://play.google.com/store/apps/details?id=com.ebest.efriend.neo",
  },
  {
    id: "toss",
    name: "토스증권",
    short: "토스",
    logo_color: "#0064FF",
    mobile_web: "https://securities.toss.im",
    deep_link: "supertoss://",
    android_store: "https://play.google.com/store/apps/details?id=viva.republica.toss",
  },
  {
    id: "kakao",
    name: "카카오페이증권",
    short: "카카오페이",
    logo_color: "#3A1D1D",
    mobile_web: "https://securities.kakaopay.com",
    deep_link: "kakaopay://",
    android_store: "https://play.google.com/store/apps/details?id=com.kakaopaycorp.stock",
  },
  {
    id: "yuanta",
    name: "유안타증권",
    short: "유안타",
    logo_color: "#CC0000",
    mobile_web: "https://m.yuanta.co.kr",
    deep_link: "yuanta://",
    android_store: "https://play.google.com/store/apps/details?id=com.yuanta.mobile.android.mts",
  },
  {
    id: "hyundai",
    name: "현대차증권",
    short: "현대차",
    logo_color: "#002C5F",
    mobile_web: "https://m.hmcib.com",
    deep_link: "hmcib://",
    android_store: "https://play.google.com/store/apps/details?id=com.hmcib.smartmts",
  },
];
